# list of Melees
require './classes'

MELEES = Array.new()

MELEES.push(Melee.new("Amphis"))
MELEES.push(Melee.new("Ankyros"))
MELEES.push(Melee.new("Ankyros Prime"))
MELEES.push(Melee.new("Atterax"))
MELEES.push(Melee.new("Bo"))
MELEES.push(Melee.new("Bo Prime"))
MELEES.push(Melee.new("Ceramic Dagger"))
MELEES.push(Melee.new("Cronus"))
MELEES.push(Melee.new("Dakra Prime"))
MELEES.push(Melee.new("Dark Dagger"))
MELEES.push(Melee.new("Dark Sword"))
MELEES.push(Melee.new("Dex Dakra"))
MELEES.push(Melee.new("Dragon Nikana"))
MELEES.push(Melee.new("Dual Cleavers"))
MELEES.push(Melee.new("Dual Ether"))
MELEES.push(Melee.new("Dual Heat Swords"))
MELEES.push(Melee.new("Dual Ichor"))
MELEES.push(Melee.new("Dual Kamas"))
MELEES.push(Melee.new("Dual Raza"))
MELEES.push(Melee.new("Dual Skana"))
MELEES.push(Melee.new("Dual Zoren"))
MELEES.push(Melee.new("Ether Daggers"))
MELEES.push(Melee.new("Ether Reaper"))
MELEES.push(Melee.new("Ether Sword"))
MELEES.push(Melee.new("Fang"))
MELEES.push(Melee.new("Fang Prime"))
MELEES.push(Melee.new("Fragor"))
MELEES.push(Melee.new("Furax"))
MELEES.push(Melee.new("Galatine"))
MELEES.push(Melee.new("Glaive"))
MELEES.push(Melee.new("Glaive Prime"))
MELEES.push(Melee.new("Gram"))
MELEES.push(Melee.new("Halikar"))
MELEES.push(Melee.new("Hate"))
MELEES.push(Melee.new("Heat Dagger"))
MELEES.push(Melee.new("Heat Sword"))
MELEES.push(Melee.new("Jat Kittag"))
MELEES.push(Melee.new("Jaw Sword"))
MELEES.push(Melee.new("Kama"))
MELEES.push(Melee.new("Karyst"))
MELEES.push(Melee.new("Kestrel"))
MELEES.push(Melee.new("Kogake"))
MELEES.push(Melee.new("Kronen"))
MELEES.push(Melee.new("Lecta"))
MELEES.push(Melee.new("Machete"))
MELEES.push(Melee.new("Machete Wraith"))
MELEES.push(Melee.new("Magistar"))
MELEES.push(Melee.new("Mire"))
MELEES.push(Melee.new("Mk1-Bo"))
MELEES.push(Melee.new("Mk1-Furax"))
MELEES.push(Melee.new("Nami Skyla"))
MELEES.push(Melee.new("Nami Solo"))
MELEES.push(Melee.new("Nikana"))
MELEES.push(Melee.new("Obex"))
MELEES.push(Melee.new("Orthos"))
MELEES.push(Melee.new("Orthos Prime"))
MELEES.push(Melee.new("Pangolin Sword"))
MELEES.push(Melee.new("Plasma Sword"))
MELEES.push(Melee.new("Prova"))
MELEES.push(Melee.new("Prova Vandal"))
MELEES.push(Melee.new("Reaper Prime"))
MELEES.push(Melee.new("Redeemer"))
MELEES.push(Melee.new("Ripkas"))
MELEES.push(Melee.new("Scindo"))
MELEES.push(Melee.new("Scindo Prime"))
MELEES.push(Melee.new("Scoliac"))
MELEES.push(Melee.new("Serro"))
MELEES.push(Melee.new("Sheev"))
MELEES.push(Melee.new("Silva And Aegis"))
MELEES.push(Melee.new("Skana"))
MELEES.push(Melee.new("Skana Prime"))
MELEES.push(Melee.new("Tipedo"))
MELEES.push(Melee.new("Tonbo"))
MELEES.push(Melee.new("Venka"))