# list of Primaries
require './classes'

PRIMARIES = Array.new()

PRIMARIES.push(Primary.new("Amprex"))
PRIMARIES.push(Primary.new("Attica"))
PRIMARIES.push(Primary.new("Boar"))
PRIMARIES.push(Primary.new("Boar Prime"))
PRIMARIES.push(Primary.new("Boltor"))
PRIMARIES.push(Primary.new("Boltor Prime"))
PRIMARIES.push(Primary.new("Braton"))
PRIMARIES.push(Primary.new("Braton Prime"))
PRIMARIES.push(Primary.new("Braton Vandal"))
PRIMARIES.push(Primary.new("Burston"))
PRIMARIES.push(Primary.new("Burston Prime"))
PRIMARIES.push(Primary.new("Buzlok"))
PRIMARIES.push(Primary.new("Cernos"))
PRIMARIES.push(Primary.new("Dera"))
PRIMARIES.push(Primary.new("Drakgoon"))
PRIMARIES.push(Primary.new("Dread"))
PRIMARIES.push(Primary.new("Flux Rifle"))
PRIMARIES.push(Primary.new("Glaxion"))
PRIMARIES.push(Primary.new("Gorgon"))
PRIMARIES.push(Primary.new("Gorgon Wraith"))
PRIMARIES.push(Primary.new("Grakata"))
PRIMARIES.push(Primary.new("Grinlok"))
PRIMARIES.push(Primary.new("Hek"))
PRIMARIES.push(Primary.new("Hind"))
PRIMARIES.push(Primary.new("Ignis"))
PRIMARIES.push(Primary.new("Karak"))
PRIMARIES.push(Primary.new("Kohm"))
PRIMARIES.push(Primary.new("Lanka"))
PRIMARIES.push(Primary.new("Latron"))
PRIMARIES.push(Primary.new("Latron Prime"))
PRIMARIES.push(Primary.new("Latron Wraith"))
PRIMARIES.push(Primary.new("Miter"))
PRIMARIES.push(Primary.new("MK1-Braton"))
PRIMARIES.push(Primary.new("MK1-Paris"))
PRIMARIES.push(Primary.new("MK1-Strun"))
PRIMARIES.push(Primary.new("Mutalist Quanta"))
PRIMARIES.push(Primary.new("Ogris"))
PRIMARIES.push(Primary.new("Opticor"))
PRIMARIES.push(Primary.new("Panthera"))
PRIMARIES.push(Primary.new("Paracyst"))
PRIMARIES.push(Primary.new("Paris"))
PRIMARIES.push(Primary.new("Paris Prime"))
PRIMARIES.push(Primary.new("Penta"))
PRIMARIES.push(Primary.new("Phage"))
PRIMARIES.push(Primary.new("Prisma Gorgon"))
PRIMARIES.push(Primary.new("Quanta"))
PRIMARIES.push(Primary.new("Snipetron"))
PRIMARIES.push(Primary.new("Snipetron Vandal"))
PRIMARIES.push(Primary.new("Sobek"))
PRIMARIES.push(Primary.new("Soma"))
PRIMARIES.push(Primary.new("Soma Prime"))
PRIMARIES.push(Primary.new("Strun"))
PRIMARIES.push(Primary.new("Strun Wraith"))
PRIMARIES.push(Primary.new("Supra"))
PRIMARIES.push(Primary.new("Sybaris"))
PRIMARIES.push(Primary.new("Synapse"))
PRIMARIES.push(Primary.new("Tetra"))
PRIMARIES.push(Primary.new("Tiberon"))
PRIMARIES.push(Primary.new("Tigris"))
PRIMARIES.push(Primary.new("Tonkor"))
PRIMARIES.push(Primary.new("Torid"))
PRIMARIES.push(Primary.new("Vectis"))
PRIMARIES.push(Primary.new("Vulkar"))