#list of Secondaries
require './classes'

SECONDARIES = Array.new()

SECONDARIES.push(Secondary.new("Acrid"))
SECONDARIES.push(Secondary.new("Afuris"))
SECONDARIES.push(Secondary.new("Akbolto"))
SECONDARIES.push(Secondary.new("Akbronco"))
SECONDARIES.push(Secondary.new("Akbronco Prime"))
SECONDARIES.push(Secondary.new("Akjagara"))
SECONDARIES.push(Secondary.new("Aklato"))
SECONDARIES.push(Secondary.new("Aklex"))
SECONDARIES.push(Secondary.new("Akmagnus"))
SECONDARIES.push(Secondary.new("Aksomati"))
SECONDARIES.push(Secondary.new("Akstiletto"))
SECONDARIES.push(Secondary.new("Akvasto"))
SECONDARIES.push(Secondary.new("Akzani"))
SECONDARIES.push(Secondary.new("Angstrum"))
SECONDARIES.push(Secondary.new("Ballistica"))
SECONDARIES.push(Secondary.new("Bolto"))
SECONDARIES.push(Secondary.new("Brakk"))
SECONDARIES.push(Secondary.new("Bronco"))
SECONDARIES.push(Secondary.new("Bronco Prime"))
SECONDARIES.push(Secondary.new("Castanas"))
SECONDARIES.push(Secondary.new("Cestra"))
SECONDARIES.push(Secondary.new("Despair"))
SECONDARIES.push(Secondary.new("Detron"))
SECONDARIES.push(Secondary.new("Dex Furis"))
SECONDARIES.push(Secondary.new("Dual Cestras"))
SECONDARIES.push(Secondary.new("Embolist"))
SECONDARIES.push(Secondary.new("Furis"))
SECONDARIES.push(Secondary.new("Gammacor"))
SECONDARIES.push(Secondary.new("Hikou"))
SECONDARIES.push(Secondary.new("Hikou Prime"))
SECONDARIES.push(Secondary.new("Kohmak"))
SECONDARIES.push(Secondary.new("Kraken"))
SECONDARIES.push(Secondary.new("Kunai"))
SECONDARIES.push(Secondary.new("Lato"))
SECONDARIES.push(Secondary.new("Lato Prime"))
SECONDARIES.push(Secondary.new("Lato Vandal"))
SECONDARIES.push(Secondary.new("Lex"))
SECONDARIES.push(Secondary.new("Lex Prime"))
SECONDARIES.push(Secondary.new("Magnus"))
SECONDARIES.push(Secondary.new("Mara Detron"))
SECONDARIES.push(Secondary.new("Marelok"))
SECONDARIES.push(Secondary.new("Mk1-Furis"))
SECONDARIES.push(Secondary.new("Mk1-Kunai"))
SECONDARIES.push(Secondary.new("Nukor"))
SECONDARIES.push(Secondary.new("Pyrana"))
SECONDARIES.push(Secondary.new("Rakta Ballistica"))
SECONDARIES.push(Secondary.new("Sancti Castanas"))
SECONDARIES.push(Secondary.new("Secura Dual Cestra"))
SECONDARIES.push(Secondary.new("Seer"))
SECONDARIES.push(Secondary.new("Sicarus"))
SECONDARIES.push(Secondary.new("Sicarus Prime"))
SECONDARIES.push(Secondary.new("Spectra"))
SECONDARIES.push(Secondary.new("Stug"))
SECONDARIES.push(Secondary.new("Synoid Gammacor"))
SECONDARIES.push(Secondary.new("Telos Akbolto"))
SECONDARIES.push(Secondary.new("Twin Gremlins"))
SECONDARIES.push(Secondary.new("Twin Vipers"))
SECONDARIES.push(Secondary.new("Tysis"))
SECONDARIES.push(Secondary.new("Vasto"))
SECONDARIES.push(Secondary.new("Vasto Prime"))
SECONDARIES.push(Secondary.new("Vaykor Marelok"))
SECONDARIES.push(Secondary.new("Viper"))
SECONDARIES.push(Secondary.new("Wraith Twin Vipers"))