#list of Warframes
require './classes'

WARFRAMES = Array.new()

WARFRAMES.push(Warframe.new("Ash"))
WARFRAMES.push(Warframe.new("Banshee"))
WARFRAMES.push(Warframe.new("Chroma"))
WARFRAMES.push(Warframe.new("Ember"))
WARFRAMES.push(Warframe.new("Ember Prime"))
WARFRAMES.push(Warframe.new("Excalibur"))
WARFRAMES.push(Warframe.new("Excalibur Prime"))
WARFRAMES.push(Warframe.new("Frost"))
WARFRAMES.push(Warframe.new("Frost Prime"))
WARFRAMES.push(Warframe.new("Hydroid"))
WARFRAMES.push(Warframe.new("Limbo"))
WARFRAMES.push(Warframe.new("Loki"))
WARFRAMES.push(Warframe.new("Loki Prime"))
WARFRAMES.push(Warframe.new("Mag"))
WARFRAMES.push(Warframe.new("Mag Prime"))
WARFRAMES.push(Warframe.new("Mesa"))
WARFRAMES.push(Warframe.new("Mirage"))
WARFRAMES.push(Warframe.new("Nekros"))
WARFRAMES.push(Warframe.new("Nova"))
WARFRAMES.push(Warframe.new("Nova Prime"))
WARFRAMES.push(Warframe.new("Nyx"))
WARFRAMES.push(Warframe.new("Nyx Prime"))
WARFRAMES.push(Warframe.new("Oberon"))
WARFRAMES.push(Warframe.new("Rhino"))
WARFRAMES.push(Warframe.new("Rhino Prime"))
WARFRAMES.push(Warframe.new("Saryn"))
WARFRAMES.push(Warframe.new("Trinity"))
WARFRAMES.push(Warframe.new("Valkyr"))
WARFRAMES.push(Warframe.new("Vauban"))
WARFRAMES.push(Warframe.new("Volt"))
WARFRAMES.push(Warframe.new("Volt Prime"))
WARFRAMES.push(Warframe.new("Zephyr"))